export const UNIVERSE = [
  {
    symbol: "ACB",
    name: "Asia Commercial Bank",
    exchange: "HOSE",
    sector: "Banking",
    currency: "VND",
  },
  {
    symbol: "VCB",
    name: "Vietcombank",
    exchange: "HOSE",
    sector: "Banking",
    currency: "VND",
  },
  {
    symbol: "VNM",
    name: "Vinamilk",
    exchange: "HOSE",
    sector: "Consumer Staples",
    currency: "VND",
  },
  {
    symbol: "FPT",
    name: "FPT Corporation",
    exchange: "HOSE",
    sector: "Technology",
    currency: "VND",
  },
  {
    symbol: "HPG",
    name: "Hoa Phat Group",
    exchange: "HOSE",
    sector: "Materials",
    currency: "VND",
  },
  {
    symbol: "TCB",
    name: "Techcombank",
    exchange: "HOSE",
    sector: "Banking",
    currency: "VND",
  },
  {
    symbol: "BID",
    name: "BIDV",
    exchange: "HOSE",
    sector: "Banking",
    currency: "VND",
  },
  {
    symbol: "MBB",
    name: "MB Bank",
    exchange: "HOSE",
    sector: "Banking",
    currency: "VND",
  },
  {
    symbol: "MWG",
    name: "Mobile World",
    exchange: "HOSE",
    sector: "Retail",
    currency: "VND",
  },
  {
    symbol: "GAS",
    name: "PV Gas",
    exchange: "HOSE",
    sector: "Energy",
    currency: "VND",
  },
  // demo US
  {
    symbol: "AAPL",
    name: "Apple Inc.",
    exchange: "NASDAQ",
    sector: "Technology",
    currency: "USD",
  },
  {
    symbol: "MSFT",
    name: "Microsoft",
    exchange: "NASDAQ",
    sector: "Technology",
    currency: "USD",
  },
  {
    symbol: "NVDA",
    name: "NVIDIA",
    exchange: "NASDAQ",
    sector: "Technology",
    currency: "USD",
  },
];
